name: docs

on:
  push:
    paths:
    - 'gapipes/**/*.py'
    - 'docs/**'

jobs:
  main:
    name: Build and push documentation to gh-pages branch
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: s-weigand/setup-conda@v1
        with:
          python-version: 3.7
      - name: Build environment
        run: |
          conda create --yes --quiet --name myenv python=3.7 pip
          source activate myenv
          # may include this to setup.py in the end
          pip install pandas
          pip install git+https://github.com/smoh/gapipes.git@master
          # NOTE: We are already in the project directory.
          pip install -e .
      - name: Set up docs dependencies
        run: |
          source activate myenv
          pip install sphinx
          pip install -U -r docs/requirements.txt
          # Additionally needs pandoc and ipython (for syntax highlighting)
          conda install -y -c conda-forge pandoc
          pip install ipython
      - name: Build documentation
        run: |
          source activate myenv
          cd docs
          make docs
      - name: Publish to gh-pages
        run: |
          mkdir ghpages
          cd ghpages
          git clone -b gh-pages --single-branch https://smoh:${{ secrets.GITHUB_TOKEN }}@github.com/smoh/gapipes.git .
          rm -rf .git *
          mv ../docs/build/html/* .
          git init
          git add -f *
          touch .nojekyll
          git add .nojekyll
          git -c "user.name=Semyeong Oh" -c "user.email=semyeong.oh@gmail.com" commit -m 'Build gh-pages'
          git push -f https://smoh:${{ secrets.GITHUB_TOKEN }}@github.com/smoh/kinesis HEAD:gh-pages
